services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Abcd1234
      POSTGRES_DB: homelab
      TZ: "Asia/Shanghai"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - homelab_net

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@homelab.com
      PGADMIN_DEFAULT_PASSWORD: Abcd1234
      PGADMIN_CONFIG_SERVER_MODE: "False"   # allows multiple users in one session
      TZ: "Asia/Shanghai"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - homelab_net

volumes:
  postgres_data:
  pgadmin_data:

networks:
  homelab_net:
