services:
  db:
    image: postgres:16.2
    container_name: pgsql
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Abcd1234
    command: postgres -c logging_collector=on -c log_destination=stderr -c log_directory=/logs
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/logs:/logs
      #- ./logs:/logs
      #- local_pgdata:/var/lib/postgresql/data
      
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@kaskade.com
      PGADMIN_DEFAULT_PASSWORD: Abcd1234
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data:
